### ISSUE TITLE
AccessControl and ERC20 Implementation

### ISSUE THREAD

**Issue by farunurisonmez** [efsoftworks/nft-marketplace-contracts#1]
Implement AccessControl and ERC20 using OpenZeppelin contracts. Explain the roles of these libraries in the contract and how they contribute to access control and ERC20 functionality.

**Comment by 0xfaru** [comment]
Development of the EFSToken contract incorporating the Solidity AccessControl module and ERC20 standards. With this last update, the token transfer functionality, permission controls, and the fundamental contract structure have been enhanced.
